In [1]:
import numpy as np
import pandas as pd

In [2]:
#import csv file with columns and turn into DataFrame
mathands = pd.read_csv("mathands_compiled_m8_columns.csv")
mathands_df = pd.DataFrame(mathands)
mathands_df

,Begin Time - ss.msec,End Time - ss.msec,Duration - ss.msec,*TIME,LHGrasp,RHInteract,RHGrasp,Interact Comment,LHInteract,Grasp Comment,LHinteract,File,File Path
0,119.006,119.382,0.376,START,NaN,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_mathands_KC.eaf,NaN
1,119.006,138.795,19.789,NaN,NaN,NaN,mg,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_mathands_KC.eaf,NaN
2,119.006,138.796,19.790,NaN,NaN,m,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_mathands_KC.eaf,NaN
3,137.203,137.597,0.394,NaN,mg,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_mathands_KC.eaf,NaN
4,137.204,137.596,0.392,NaN,NaN,NaN,NaN,NaN,m,NaN,NaN,001_08_071807_07172018EP_mathands_KC.eaf,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2530,390.126,390.392,0.266,NaN,NaN,m,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_mathands_DH.eaf,NaN
2531,394.308,399.769,5.461,NaN,NaN,m,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_mathands_DH.eaf,NaN
2532,394.407,399.781,5.374,NaN,NaN,NaN,mg,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_mathands_DH.eaf,NaN
2533,404.946,405.081,0.135,End Toy Play - by BK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_mathands_DH.eaf,NaN
2534,674.719,675.215,0.496,END,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_mathands_DH.eaf,NaN

In [3]:
#keep time, interact and file name columns
mathands_df = mathands_df[['Begin Time - ss.msec','End Time - ss.msec','RHInteract','LHInteract', 'LHinteract','File']]

#rename columns 
mathands_df = mathands_df.rename(columns={'Begin Time - ss.msec':'Begin'})
mathands_df = mathands_df.rename(columns={'End Time - ss.msec':'End'})


#rename the file names into just ID and month (i.e.'001_08')
for i in mathands_df['File']:
    newfilename = i[0:6]
    mathands_df['File'] = mathands_df['File'].replace(i,newfilename)

In [4]:
#turn all contents in Interact columns into string
mathands_df[['RHInteract','LHInteract','LHinteract']] = mathands_df[['RHInteract','LHInteract','LHinteract']].astype(str)

#keep only 'm',' a', 'i' in RHInteract and LHInteract
for i in mathands_df['RHInteract']:
    if i == 'nan':
        no_interact = ''
        mathands_df['RHInteract'] = mathands_df['RHInteract'].replace(i,no_interact)  

for i in mathands_df['LHInteract']:
    if i == 'nan':
        no_interact = ''
        mathands_df['LHInteract'] = mathands_df['LHInteract'].replace(i,no_interact)    

#there are two left hand interact columns
#find values that are in LHinteract and move them to LHInteract and remove column 
for index,row in mathands_df.iterrows():
    if row['LHinteract'] != 'nan':
        mathands_df.at[index,'LHInteract']= row['LHinteract']
    else:
        continue
mathands_df = mathands_df.drop(['LHinteract'], axis=1)

In [5]:
#create new columns for three toys
#iterate through every row for each toy type both RHInteract and LHInteract

#musical toy
mathands_df['m'] = ""
for index,row in mathands_df.iterrows():
    if row['RHInteract'] == 'm':
        mathands_df.at[index,'m']= 'mom'
        
for index,row in mathands_df.iterrows():
    if row['LHInteract'] == 'm':
        mathands_df.at[index,'m']= 'mom'

#inanimate toy 
mathands_df['i'] = ""
for index,row in mathands_df.iterrows():
    if row['RHInteract'] == 'i':
        mathands_df.at[index,'i']= 'mom'
        
for index,row in mathands_df.iterrows():
    if row['LHInteract'] == 'i':
        mathands_df.at[index,'i']= 'mom'

#animate toy  
mathands_df['a'] = ""
for index,row in mathands_df.iterrows():
    if row['RHInteract'] == 'a':
        mathands_df.at[index,'a']= 'mom'

for index,row in mathands_df.iterrows():
    if row['LHInteract'] == 'a':
        mathands_df.at[index,'a']= 'mom'

In [6]:
#only keep time, toy types, and file columns
#reindex to make sure order is corrrect 
mathands_df = mathands_df.drop(labels=['RHInteract','LHInteract'], axis=1)
columns_order = ['Begin', 'End','m','i','a','File']
mathands_df = mathands_df.reindex(columns=columns_order)

In [7]:
mathands_df

        Begin      End    m i  a     File
0     119.006  119.382             001_08
1     119.006  138.795             001_08
2     119.006  138.796  mom        001_08
3     137.203  137.597             001_08
4     137.204  137.596  mom        001_08
...       ...      ...  ... .. ..     ...
2530  390.126  390.392  mom        048_08
2531  394.308  399.769  mom        048_08
2532  394.407  399.781             048_08
2533  404.946  405.081             048_08
2534  674.719  675.215             048_08

[2535 rows x 6 columns]

In [8]:
#import csv file with columns and turn into DataFrame
babyhands = pd.read_csv("babyhands_compiled_m8_columns.csv")
babyhands_df = pd.DataFrame(babyhands)

In [9]:
babyhands_df

,Begin Time - ss.msec,End Time - ss.msec,*TIME,Motion,LHGrasp,RHInteract,Mouthing,RHGrasp,Interact Comment,LHInteract,Mom Action,Grasp Comment,Mouth,Mom Actions,LHinteract,Mom Grab,File,File Path
0,119.000,142.899,NaN,NaN,NaN,i,NaN,ig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_babyhands_TD.eaf,NaN
1,119.006,119.382,START,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_babyhands_TD.eaf,NaN
2,123.240,139.679,NaN,NaN,NaN,NaN,NaN,NaN,NaN,i,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_babyhands_TD.eaf,NaN
3,123.557,139.679,NaN,NaN,ig,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_babyhands_TD.eaf,NaN
4,124.417,130.089,NaN,NaN,NaN,NaN,im,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,001_08_071807_07172018EP_babyhands_TD.eaf,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3370,394.459,394.717,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,momgrab,NaN,NaN,048_08_020409MA_SYNC_CLEAN_babyhands_TD.eaf,NaN
3371,400.240,406.797,NaN,NaN,NaN,m,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_babyhands_TD.eaf,NaN
3372,401.167,403.871,NaN,shak,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_babyhands_TD.eaf,NaN
3373,404.946,405.081,End Toy Play - by BK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_babyhands_TD.eaf,NaN
3374,674.719,675.215,END,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,048_08_020409MA_SYNC_CLEAN_babyhands_TD.eaf,NaN

In [10]:
#keep only time, interact, mom action, and file columns
babyhands_df = babyhands_df[['Begin Time - ss.msec','End Time - ss.msec','RHInteract','LHInteract', 'LHinteract',
                             'Mom Action','Mom Actions', "Mom Grab",'File']]

#rename columns
babyhands_df = babyhands_df.rename(columns={'Begin Time - ss.msec':'Begin'})
babyhands_df = babyhands_df.rename(columns={'End Time - ss.msec':'End'})

#rename the file names into just ID and month (i.e.'001_08')
for i in babyhands_df['File']:
    newfilename = i[0:6]
    babyhands_df['File'] = babyhands_df['File'].replace(i,newfilename)

In [11]:
#turn all contents in both Interact column and Mom columns into string
babyhands_df[['RHInteract', 'LHInteract','LHinteract','Mom Action','Mom Actions','Mom Grab']] = babyhands_df[['RHInteract', 'LHInteract','LHinteract','Mom Action','Mom Actions','Mom Grab']].astype(str) 

#keep only 'm',' a', 'i' in Interact columns 
for i in babyhands_df['RHInteract']:
    if i == 'nan':
        no_interact = ''
        babyhands_df['RHInteract'] = babyhands_df['RHInteract'].replace(i,no_interact)  

for i in babyhands_df['LHInteract']:
    if i == 'nan':
        no_interact = ''
        babyhands_df['LHInteract'] = babyhands_df['LHInteract'].replace(i,no_interact)  
        
#there are two left hand interact colums
#move all non empty values in LHinteract into LHInteract and remove LHinteract
for index,row in babyhands_df.iterrows():
    if row['LHinteract'] != 'nan':
        babyhands_df.at[index,'LHInteract']= row['LHinteract']
    else:
        continue
babyhands_df = babyhands_df.drop(['LHinteract'], axis=1)
        
#there are three Mom columns
#move all non empty values in Mom Action and Mom grab into Mom Actions and only keep Mom Actions
for index,row in babyhands_df.iterrows():
    if row['Mom Action'] != 'nan':
        babyhands_df.at[index,'Mom Actions']= row['Mom Action']
    else:
        continue
babyhands_df = babyhands_df.drop(['Mom Action'], axis=1)

for index,row in babyhands_df.iterrows():        
    if row['Mom Grab'] != 'nan':
        babyhands_df.at[index,'Mom Actions']= row['Mom Grab']
    else:
        continue
babyhands_df = babyhands_df.drop(['Mom Grab'], axis=1)

for i in babyhands_df['Mom Actions']:
    if i == 'nan':
        no_interact = ''
        babyhands_df['Mom Actions'] = babyhands_df['Mom Actions'].replace(i,no_interact)

In [12]:
#create new columns for three toys
#iterate through every row for each toy type both RHInteract and LHInteract

#musical toy
babyhands_df['m'] = ""
for index,row in babyhands_df.iterrows():
    if row['RHInteract'] == 'm':
        babyhands_df.at[index,'m']= 'inf'
        
for index,row in babyhands_df.iterrows():
    if row['LHInteract'] == 'm':
        babyhands_df.at[index,'m']= 'inf'

#inanimate toy 
babyhands_df['i'] = ""
for index,row in babyhands_df.iterrows():
    if row['RHInteract'] == 'i':
        babyhands_df.at[index,'i']= 'inf'
        
for index,row in babyhands_df.iterrows():
    if row['LHInteract'] == 'i':
        babyhands_df.at[index,'i']= 'inf'

#animate toy  
babyhands_df['a'] = ""
for index,row in babyhands_df.iterrows():
    if row['RHInteract'] == 'a':
        babyhands_df.at[index,'a']= 'inf'

for index,row in babyhands_df.iterrows():
    if row['LHInteract'] == 'a':
        babyhands_df.at[index,'a']= 'inf'

In [13]:
#only keep time, toy types, and file columns
#reindex to make sure order is corrrect 
babyhands_df = babyhands_df.drop(labels=['RHInteract','LHInteract'], axis=1)
columns_order = ['Begin', 'End','m','i','a','Mom Actions','File']
babyhands_df = babyhands_df.reindex(columns=columns_order)

In [14]:
babyhands_df

        Begin      End    m    i a  Mom Actions    File
0     119.000  142.899       inf                 001_08
1     119.006  119.382                           001_08
2     123.240  139.679       inf                 001_08
3     123.557  139.679                           001_08
4     124.417  130.089                           001_08
...       ...      ...  ...  ... ..         ...     ...
3370  394.459  394.717                  momgrab  048_08
3371  400.240  406.797  inf                      048_08
3372  401.167  403.871                           048_08
3373  404.946  405.081                           048_08
3374  674.719  675.215                           048_08

[3375 rows x 7 columns]

In [15]:
mathands_df

        Begin      End    m i  a     File
0     119.006  119.382             001_08
1     119.006  138.795             001_08
2     119.006  138.796  mom        001_08
3     137.203  137.597             001_08
4     137.204  137.596  mom        001_08
...       ...      ...  ... .. ..     ...
2530  390.126  390.392  mom        048_08
2531  394.308  399.769  mom        048_08
2532  394.407  399.781             048_08
2533  404.946  405.081             048_08
2534  674.719  675.215             048_08

[2535 rows x 6 columns]

In [16]:
#merge babyhands and mathands
matbaby_df = pd.merge(babyhands_df, mathands_df, how='outer', on=['Begin','End'],
                     suffixes = ('_inf','_mom'))

In [17]:
#change all contents in string 
matbaby_df[['m_inf', 'i_inf','a_inf','Mom Actions','File_inf',
                'm_mom', 'i_mom', 'a_mom','File_mom']] = matbaby_df[['m_inf', 'i_inf','a_inf','Mom Actions','File_inf',
                'm_mom', 'i_mom', 'a_mom','File_mom']].astype(str)

In [18]:
#correspond file name of mom and inf to each other
for index,row in matbaby_df.iterrows():
    if row['File_mom'] == 'nan':
        matbaby_df.at[index,'File_mom']= row['File_inf']
    else:
        continue
        
for index,row in matbaby_df.iterrows():   
    if row['File_inf'] == 'nan':
        matbaby_df.at[index,'File_inf']= row['File_mom']
    else:
        continue

#check file names are the same
#if they are, keep only one and rename to just File
for index,row in matbaby_df.iterrows():   
    if row['File_inf'] != row['File_mom']:
        print('file name not the same')
    else:
        continue   
        
matbaby_df = matbaby_df.drop('File_inf', axis=1)
matbaby_df = matbaby_df.rename(columns={'File_mom':'File'})

In [19]:
matbaby_df

        Begin      End m_inf i_inf a_inf Mom Actions m_mom i_mom a_mom    File
0     119.000  142.899         inf                     nan   nan   nan  001_08
1     119.006  119.382                                                  001_08
2     123.240  139.679         inf                     nan   nan   nan  001_08
3     123.557  139.679                                 nan   nan   nan  001_08
4     124.417  130.089                                 nan   nan   nan  001_08
...       ...      ...   ...   ...   ...         ...   ...   ...   ...     ...
5800  383.210  386.686   nan   nan   nan         nan                    048_08
5801  389.627  389.795   nan   nan   nan         nan   mom              048_08
5802  390.126  390.392   nan   nan   nan         nan   mom              048_08
5803  394.308  399.769   nan   nan   nan         nan   mom              048_08
5804  394.407  399.781   nan   nan   nan         nan                    048_08

[5805 rows x 10 columns]

In [20]:
for index,row in matbaby_df.iterrows():
    if row['m_inf'] == 'nan':
        matbaby_df.at[index,'m_inf']= ''
    else:
        continue

for index,row in matbaby_df.iterrows():
    if row['i_inf'] == 'nan':
        matbaby_df.at[index,'i_inf']= ''
    else:
        continue

for index,row in matbaby_df.iterrows():
    if row['a_inf'] == 'nan':
        matbaby_df.at[index,'a_inf']= ''
    else:
        continue
        
for index,row in matbaby_df.iterrows():
    if row['m_mom'] == 'nan':
        matbaby_df.at[index,'m_mom']= ''
    else:
        continue

for index,row in matbaby_df.iterrows():
    if row['i_mom'] == 'nan':
        matbaby_df.at[index,'i_mom']= ''
    else:
        continue

for index,row in matbaby_df.iterrows():
    if row['a_mom'] == 'nan':
        matbaby_df.at[index,'a_mom']= ''
    else:
        continue

for index,row in matbaby_df.iterrows():
    if row['Mom Actions'] == 'nan':
        matbaby_df.at[index,'Mom Actions']= ''
    else:
        continue

In [21]:
for index,row in matbaby_df.iterrows():   
    mus_m = row['m_mom'] == 'mom'
    mus_i = row['m_inf'] == 'inf'
    if mus_m & mus_i == True:
        print(index)

In [22]:
matbaby_df

        Begin      End m_inf i_inf a_inf Mom Actions m_mom i_mom a_mom    File
0     119.000  142.899         inf                                      001_08
1     119.006  119.382                                                  001_08
2     123.240  139.679         inf                                      001_08
3     123.557  139.679                                                  001_08
4     124.417  130.089                                                  001_08
...       ...      ...   ...   ...   ...         ...   ...   ...   ...     ...
5800  383.210  386.686                                                  048_08
5801  389.627  389.795                                 mom              048_08
5802  390.126  390.392                                 mom              048_08
5803  394.308  399.769                                 mom              048_08
5804  394.407  399.781                                                  048_08

[5805 rows x 10 columns]